#version: "3.3"
services:
  housingmarketadvisorapi_api:
    container_name: api
    build:
      context: .
      dockerfile: ./HousingMarketAdvisor.API/Dockerfile
    ports:
      - "9000:443"
      - "9001:80"
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: ./HousingMarketAdvisor.Gateway/Dockerfile
    links:
      - housingmarketadvisorapi_api
    ports:
      - "9003:443"
      - "9004:80"
  
  HMA1:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
      
  HMA2:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1439:1433"
    
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"